# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alison Strommer
email: alison.strommer@gmail.com
description: Welcome everyone! This site shall give you a good insight into my most recent activities, uploads and news feed.
I will be updating the site periodically so please subscribe to my content.
baseurl: "/jekyll-wing-template" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: amlassiter85
github_username:  astrommer

# Build settings
markdown: kramdown
